import {Router} from 'express';import {z} from 'zod';import {prisma} from '../db';import {authenticate,requireAdmin,AuthRequest} from '../middleware/auth';
const router=Router();
const priceJson=(p:any)=>({main:{per30:Number(p.main_per30_usd),oneDay:Number(p.main_one_day_usd)},wall:{per30:Number(p.wall_per30_usd),oneDay:Number(p.wall_one_day_usd)},corner:{per30:Number(p.corner_per30_usd),oneDay:Number(p.corner_one_day_usd)},updatedAt:p.updated_at});
async function pricing(){await prisma.$executeRaw`INSERT INTO pricing_settings(id) VALUES ('default') ON CONFLICT(id) DO NOTHING`;const r=await prisma.$queryRaw<any[]>`SELECT * FROM pricing_settings WHERE id='default'`;if(!r[0])throw new Error('Pricing unavailable');return r[0]}
router.get('/pricing',async(_q,res,next)=>{try{res.json(priceJson(await pricing()))}catch(e){next(e)}});
router.get('/pricing/admin',authenticate,requireAdmin,async(_q,res,next)=>{try{res.json(priceJson(await pricing()))}catch(e){next(e)}});
router.patch('/pricing/admin',authenticate,requireAdmin,async(req,res,next)=>{try{const d=z.object({mainPer30:z.number().positive(),mainOneDay:z.number().positive(),wallPer30:z.number().positive(),wallOneDay:z.number().positive(),cornerPer30:z.number().positive(),cornerOneDay:z.number().positive()}).parse(req.body);await prisma.$executeRaw`UPDATE pricing_settings SET main_per30_usd=${d.mainPer30},main_one_day_usd=${d.mainOneDay},wall_per30_usd=${d.wallPer30},wall_one_day_usd=${d.wallOneDay},corner_per30_usd=${d.cornerPer30},corner_one_day_usd=${d.cornerOneDay},updated_at=CURRENT_TIMESTAMP WHERE id='default'`;res.json(priceJson(await pricing()))}catch(e){next(e)}});
router.get('/stats',authenticate,requireAdmin,async(_req,res,next)=>{try{const [u,b,a,tx,v]=await Promise.all([prisma.user.count(),prisma.billboard.count(),prisma.advertisement.count(),prisma.transaction.count(),prisma.siteVisit.count()]);const active=await prisma.booking.count({where:{status:'ACTIVE',endDate:{gt:new Date()}}});const paid=await prisma.booking.findMany({where:{payment:{status:'SUCCEEDED'}},select:{amount:true}});res.json({totalUsers:u,totalBillboards:b,totalAds:a,totalTransactions:tx,totalSiteVisits:v,activeBookings:active,revenue:paid.reduce((s,x)=>s+Number(x.amount||0),0)})}catch(e){next(e)}});
router.get('/users',authenticate,requireAdmin,async(req,res,next)=>{try{const w:any={};if(req.query.search)w.OR=[{username:{contains:String(req.query.search),mode:'insensitive'}},{email:{contains:String(req.query.search),mode:'insensitive'}},{displayName:{contains:String(req.query.search),mode:'insensitive'}}];if(req.query.role)w.role=req.query.role;res.json(await prisma.user.findMany({where:w,include:{wallet:true,_count:{select:{bids:true,advertisements:true,campaigns:true}}},orderBy:{createdAt:'desc'},take:100}))}catch(e){next(e)}});
router.patch('/users/:id/status',authenticate,requireAdmin,async(req:AuthRequest,res,next)=>{try{if(req.params.id===req.user!.id)return res.status(400).json({error:'You cannot deactivate your own admin account.'});res.json(await prisma.user.update({where:{id:req.params.id},data:{isActive:Boolean(req.body?.isActive)}}))}catch(e){next(e)}});
router.patch('/users/:id/role',authenticate,requireAdmin,async(req:AuthRequest,res,next)=>{try{if(!['USER','ADMIN'].includes(req.body?.role))return res.status(400).json({error:'Invalid role'});if(req.params.id===req.user!.id&&req.body.role!=='ADMIN')return res.status(400).json({error:'You cannot remove your own admin role.'});res.json(await prisma.user.update({where:{id:req.params.id},data:{role:req.body.role}}))}catch(e){next(e)}});
router.get('/bookings',authenticate,requireAdmin,async(_req,res,next)=>{try{res.json(await prisma.booking.findMany({include:{user:{select:{email:true,username:true,displayName:true}},billboard:{select:{name:true,type:true}},advertisement:true},orderBy:{createdAt:'desc'},take:250}))}catch(e){next(e)}});
router.patch('/bookings/:id/cancel',authenticate,requireAdmin,async(req,res,next)=>{try{res.json(await prisma.$transaction(async tx=>{const b=await tx.booking.findUnique({where:{id:req.params.id}});if(!b)throw Object.assign(new Error('Booking not found'),{status:404});if(['CANCELLED','EXPIRED'].includes(b.status))return b;return tx.booking.update({where:{id:b.id},data:{status:'CANCELLED'}})}))}catch(e){next(e)}});
router.get('/transactions',authenticate,requireAdmin,async(_req,res,next)=>{try{res.json(await prisma.transaction.findMany({include:{user:{select:{username:true,displayName:true}}},orderBy:{createdAt:'desc'},take:200}))}catch(e){next(e)}});
router.get('/advertisements',authenticate,requireAdmin,async(req,res,next)=>{try{const w:any={};if(req.query.status)w.status=req.query.status;res.json(await prisma.advertisement.findMany({where:w,include:{user:{select:{username:true,displayName:true}},campaigns:{include:{billboard:true}}},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});
router.patch('/advertisements/:id/status',authenticate,requireAdmin,async(req,res,next)=>{try{const s=String(req.body?.status||'');if(!['PENDING','APPROVED','REJECTED','DISABLED'].includes(s))return res.status(400).json({error:'Invalid advertisement status'});res.json(await prisma.advertisement.update({where:{id:req.params.id},data:{status:s}}))}catch(e){next(e)}});
router.get('/billboards',authenticate,requireAdmin,async(_req,res,next)=>{try{res.json(await prisma.billboard.findMany({include:{bookings:{where:{status:'ACTIVE',endDate:{gt:new Date()}},take:1,include:{user:{select:{displayName:true,username:true}}}},_count:{select:{bookings:true,trafficAnalytics:true}}},orderBy:{createdAt:'desc'},take:300}))}catch(e){next(e)}});
router.get('/active-visitors',authenticate,requireAdmin,async(_req,res,next)=>{try{const r=await prisma.trafficAnalytics.findMany({where:{timestamp:{gte:new Date(Date.now()-300000)}},orderBy:{timestamp:'desc'},take:100});res.json({recentTraffic:r,totalRecentVisitors:r.reduce((s,x)=>s+x.nearbyVisitors,0)})}catch(e){next(e)}});
export {router as adminRouter};
