import { Link, useLocation } from 'react-router-dom';

type PageKey = 'about'|'how-it-works'|'faq'|'rules'|'terms'|'privacy'|'refund-policy'|'contact'|'pricing';

const CONTENT: Record<PageKey,{title:string;lead:string;sections:{heading:string;body:string[]}[]}> = {
  about:{title:'About UrbanCity',lead:'UrbanCity is an interactive digital city where anyone can discover and book advertising spaces displayed inside a shared 3D environment.',sections:[
    {heading:'What UrbanCity does',body:['UrbanCity makes advertising inventory interactive. Users can explore available billboards, review locations and pricing, upload an advertisement, and book an available space for the selected duration.','When a booking is active, the advertiser’s creative can be displayed on the corresponding advertising space in UrbanCity.']},
    {heading:'Our purpose',body:['We aim to make digital advertising spaces easier to discover and understand by presenting them in an interactive city experience rather than only as a traditional list of placements.']},
    {heading:'Operator and support',body:['UrbanCity is operated by Faraz as a SaaS service based in India. For support, booking or payment questions, contact farazrasool643@gmail.com.']}
  ]},
  'how-it-works':{title:'How It Works',lead:'Booking an advertising space in UrbanCity is designed to be straightforward.',sections:[
    {heading:'1. Explore',body:['Enter UrbanCity and move around the city to discover available advertising spaces.']},
    {heading:'2. Choose a space',body:['Interact with a billboard to review its information, traffic category, booking duration and price.']},
    {heading:'3. Add your creative',body:['Provide your company name and advertisement details. You may upload a supported image and optionally provide a destination link. You are responsible for ensuring that your creative and destination link are lawful and that you have the necessary rights to use them.']},
    {heading:'4. Pay and activate',body:['Complete payment through the available secure payment checkout. A booking becomes active only after payment is successfully confirmed. The booking period begins when payment is successfully confirmed, subject to the platform booking process.']},
    {heading:'5. Manage your booking',body:['During an active booking, eligible account controls allow you to manage the creative associated with your booked advertising space. Changes remain subject to our Rules and applicable law.']}
  ]},
  faq:{title:'Frequently Asked Questions',lead:'Clear answers to common questions about UrbanCity.',sections:[
    {heading:'What is UrbanCity?',body:['UrbanCity is an interactive platform for discovering and booking digital advertising spaces in a shared 3D city environment.']},
    {heading:'Who can use UrbanCity?',body:['UrbanCity is available to individuals and businesses. You are responsible for ensuring that your use of the service and advertising activity is lawful.']},
    {heading:'Do I need an account?',body:['Yes. An account is required for actions that require identifying and managing a user, including booking or other account-based features.']},
    {heading:'How is the price calculated?',body:['The booking panel shows the applicable price before checkout. Current starting prices are $0.50 per 30 minutes for Corner spaces, $0.69 per 30 minutes for Wall spaces and $0.90 per 30 minutes for Main spaces. The final price can vary by space, duration and package.']},
    {heading:'When does my booking start?',body:['The booking period begins when payment is successfully confirmed. Opening checkout alone does not start the booking.']},
    {heading:'What currency will I see at checkout?',body:['UrbanCity prices are displayed in USD. The payment checkout may present the payable amount in another currency depending on the payment provider and payment setup. Always review the final amount shown immediately before payment.']},
    {heading:'Are taxes included?',body:['The displayed UrbanCity prices are currently shown before any applicable taxes. Where taxes or legally required charges apply, they may be handled and displayed as required at checkout.']},
    {heading:'Can I cancel a booking?',body:['Customer cancellations are not generally refundable before or after a booking starts, except where a refund is required by applicable law or under our Refund & Cancellation Policy.']},
    {heading:'What if I paid but my booking was not activated?',body:['Contact support with your account email and payment reference. If payment was successfully received but the paid booking was not activated, we will investigate and provide a refund where applicable under our policy.']},
    {heading:'What if I am charged twice?',body:['Contact support with both payment references. Confirmed duplicate payments will be investigated and refunded where appropriate.']},
    {heading:'Can my advertisement be rejected or removed?',body:['Yes. We may reject, disable or remove advertising content that violates our Rules, Terms, applicable law, third-party rights or platform safety requirements.']},
    {heading:'Do visitor or footfall numbers guarantee advertising results?',body:['No. Visitor and footfall figures are provided for informational purposes and do not guarantee impressions, views, clicks, conversions, leads, sales or other advertising results.']},
    {heading:'Where can I ask for help?',body:['Contact us at farazrasool643@gmail.com. For payment issues, include your account email, booking or payment reference, date and a clear description of the issue.']}
  ]},
  rules:{title:'UrbanCity Rules',lead:'These rules help keep UrbanCity safe, useful and fair for everyone.',sections:[
    {heading:'Use the platform responsibly',body:['Do not interfere with the platform, attempt to gain unauthorized access, disrupt other users, or misuse accounts or payment systems. Do not use bots or abusive automation to manipulate bookings, traffic measurements or other platform features.']},
    {heading:'Advertising content',body:['You are responsible for the content you submit and for having the rights and permissions needed to use it. Do not submit unlawful, deceptive, infringing, hateful, sexually explicit, malicious or otherwise prohibited content.','Advertising must not promote scams, fraudulent schemes, illegal gambling, illegal drugs, unlawful weapons, counterfeit goods, phishing or malware, or misleading medical/health claims. We may restrict additional categories where reasonably necessary for safety, legal compliance or platform integrity.']},
    {heading:'Advertiser rights and responsibility',body:['You confirm that you have the rights, licences and permissions necessary for all logos, trademarks, images, text, videos, music, claims and links included in your advertisement. You are responsible for the accuracy and legality of claims made in your advertisement and for the destination website or service to which you link.']},
    {heading:'Accurate information',body:['Keep your account and advertising information accurate. Do not impersonate another person or business or submit information intended to mislead users.']},
    {heading:'Fair access',body:['Do not use bots or abusive automation to manipulate bookings, auctions, traffic measurements or other platform features unless we explicitly permit it.']},
    {heading:'Enforcement',body:['We may investigate violations and take appropriate action, including rejecting, restricting, removing or disabling advertising content, cancelling a booking, restricting access or suspending an account where permitted by our Terms and applicable law.']}
  ]},
  terms:{title:'Terms & Conditions',lead:'These Terms explain the conditions for using UrbanCity and booking advertising services through the platform.',sections:[
    {heading:'1. Acceptance and eligibility',body:['By accessing or using UrbanCity, you agree to these Terms, our Privacy Policy, Rules and Refund & Cancellation Policy. If you do not agree, please do not use the service. UrbanCity is available to individuals and businesses, subject to applicable law. You are responsible for ensuring that you are legally able to enter into the relevant transaction.']},
    {heading:'2. Accounts',body:['You are responsible for safeguarding your login credentials and for activity performed through your account. Provide accurate information and notify us if you believe your account has been accessed without permission.']},
    {heading:'3. Advertising bookings',body:['UrbanCity displays advertising inventory, availability, durations and prices through the platform. A booking is subject to availability and successful payment confirmation. The booking period begins when payment is successfully confirmed. The maximum booking duration is two days. We may correct obvious pricing, technical or availability errors before activation where permitted by law.']},
    {heading:'4. Pricing, currency and taxes',body:['Current starting prices are $0.50 per 30 minutes for Corner spaces, $0.69 per 30 minutes for Wall spaces and $0.90 per 30 minutes for Main spaces. Final pricing may vary by space, duration and package. Prices are displayed in USD and are currently shown before applicable taxes. The payment provider may display the payable amount in a local currency or another supported currency. The final amount shown before payment is the amount presented for that transaction.']},
    {heading:'5. Payments',body:['Payments are processed through third-party payment providers. You must provide accurate payment information and complete the provider’s checkout process. UrbanCity does not intend to store full payment card details on its own servers when a provider-hosted checkout is used. If payment succeeds but a paid booking is not activated, contact us promptly; we will investigate and refund where applicable under the Refund & Cancellation Policy. Confirmed duplicate payments will be investigated and refunded where appropriate.']},
    {heading:'6. Cancellations and refunds',body:['Customer cancellations are not generally refundable before or after a booking starts, except where a refund is required by applicable law or expressly provided under our Refund & Cancellation Policy. This does not limit any mandatory rights that cannot legally be excluded.']},
    {heading:'7. Your content and rights',body:['You retain responsibility for the advertising content you provide and confirm that you have the rights and permissions required to use it. By submitting content for display, you give UrbanCity the limited permission necessary to store, process and display that content for operating your booking and the platform.']},
    {heading:'8. Content review and removal',body:['UrbanCity does not promise that every submitted advertisement will be accepted or remain displayed. We may reject, suspend, disable or remove an advertisement that violates our Rules, these Terms, applicable law, third-party rights or reasonable platform safety requirements.']},
    {heading:'9. Advertising performance and platform metrics',body:['Visitor, footfall, traffic and other platform metrics are provided for informational purposes and may change. They are not guarantees of impressions, views, clicks, conversions, leads, sales or any particular advertising performance.']},
    {heading:'10. Third-party links and services',body:['Advertisements may contain links to third-party websites or services. UrbanCity does not control those destinations and is not responsible for their content, availability, security, products, services or practices. Payments may also be processed by third-party providers under their own terms and privacy policies.']},
    {heading:'11. Availability and technical issues',body:['We work to keep UrbanCity available, but uninterrupted or error-free operation cannot be guaranteed. Features may be updated, changed or discontinued as the platform evolves. If a significant technical problem attributable to UrbanCity materially prevents delivery of a confirmed paid booking, contact support and we will investigate an appropriate remedy under the Refund & Cancellation Policy.']},
    {heading:'12. Prohibited use',body:['You must not use UrbanCity for unlawful activity, fraud, infringement, unauthorized access, malware distribution, manipulation of platform metrics or any activity prohibited by our Rules.']},
    {heading:'13. Limitation of liability',body:['To the maximum extent permitted by applicable law, UrbanCity is not responsible for indirect, incidental, special or consequential losses arising from use of the service, third-party services, advertising performance, temporary unavailability or third-party destination websites. Nothing in these Terms excludes liability or rights that cannot legally be excluded.']},
    {heading:'14. Changes to the service and Terms',body:['We may update the service and these Terms as UrbanCity develops. The current version published on this page applies from the time it is posted. Where required by applicable law, we will provide any additional notice required for material changes.']},
    {heading:'15. Contact',body:['For questions about these Terms, bookings or payments, contact farazrasool643@gmail.com.']}
  ]},
  privacy:{title:'Privacy Policy',lead:'This policy explains, in plain language, how UrbanCity may handle personal information when you use the platform.',sections:[
    {heading:'1. Who operates the service',body:['UrbanCity is operated by Faraz as a SaaS service based in India. For privacy questions or data requests, contact farazrasool643@gmail.com.']},
    {heading:'2. Information we may collect',body:['This can include account information such as your name or display name, email address and phone number where provided for account, booking or payment-related purposes. We may also process advertising information and creative files you submit.','We may process technical information needed to operate and secure the service, such as device, browser, IP address, log and security information.']},
    {heading:'3. How information is used',body:['We use information to provide accounts and platform features, process and manage bookings and payments, communicate about the service, support users, prevent abuse and fraud, maintain security, troubleshoot technical problems and comply with legal obligations.']},
    {heading:'4. Payments',body:['Payments are processed through third-party payment providers. UrbanCity does not intend to store full payment card details on its own servers when a provider-hosted checkout is used. The payment provider may process payment and related information according to its own terms and privacy policy.']},
    {heading:'5. Advertising uploads',body:['Creative files and related information may be stored with our infrastructure and hosting providers so they can be processed, displayed and managed through UrbanCity.']},
    {heading:'6. Sharing and service providers',body:['We may use trusted service providers for hosting, storage, databases, payments, security, communications and other functions required to operate UrbanCity. Current infrastructure includes Vercel, Render and Supabase, and payment processing may involve our selected payment provider. We share information only as reasonably necessary for those services, legal requirements, fraud prevention or protection of the platform and users.']},
    {heading:'7. International processing',body:['Because UrbanCity uses third-party infrastructure and payment services, personal information may be processed in countries other than the country where you live. Where applicable, we will use appropriate safeguards required by law for such processing.']},
    {heading:'8. Retention',body:['We retain personal information for as long as reasonably necessary for the purposes described in this policy, including operating accounts, providing bookings, maintaining security, resolving disputes and meeting legal or accounting obligations. Account contact information such as email address and phone number may be retained while reasonably needed for these purposes.']},
    {heading:'9. Cookies and similar technologies',body:['UrbanCity does not currently use non-essential cookies for advertising or tracking. Essential technologies may be used where necessary to operate sessions, authentication, security or requested functionality.']},
    {heading:'10. Your choices and rights',body:['Depending on applicable law, you may have rights to request access, correction, deletion, restriction, objection, portability or other information about your personal data. Contact farazrasool643@gmail.com to make a privacy request. We may need to verify your identity before completing a request.']},
    {heading:'11. Security',body:['We use reasonable technical and organizational measures intended to protect information, but no internet or storage system can be guaranteed completely secure.']},
    {heading:'12. Updates',body:['We may update this policy as UrbanCity develops. The current version published on this page applies from the time it is posted.']}
  ]},
  'refund-policy':{title:'Refund & Cancellation Policy',lead:'Please read this policy before making a booking.',sections:[
    {heading:'Before you pay',body:['The booking panel shows the selected advertising space, duration and price before checkout. Please review these details carefully before completing payment.']},
    {heading:'Customer cancellation',body:['Customer-requested cancellations are not generally refundable, whether requested before or after the booking starts. This policy does not limit any mandatory consumer rights that apply to you under applicable law.']},
    {heading:'When a booking starts',body:['The booking period begins when payment is successfully confirmed. Opening checkout or entering payment details without successful confirmation does not start the booking.']},
    {heading:'Paid but not activated',body:['If payment has been successfully received but the corresponding paid booking is not activated, contact us promptly with the payment and booking details. We will investigate and refund the payment where the paid booking was not activated, subject to verification and any applicable legal requirements.']},
    {heading:'Duplicate payments',body:['If you believe the same booking was charged more than once, contact us with the relevant payment references. Confirmed duplicate payments will be investigated and refunded where appropriate.']},
    {heading:'Technical service problems',body:['If a significant technical problem attributable to UrbanCity materially prevents delivery of a confirmed paid booking, contact us with the booking details. We may, depending on the circumstances, restore service, reschedule time, provide credit or issue a refund. This is not a guarantee of a particular remedy for every interruption.']},
    {heading:'Advertisement rejection or removal',body:['We may reject or remove advertisements that violate our Rules, Terms, applicable law or third-party rights. Rejection or removal does not automatically create a refund entitlement where the advertiser’s content caused the issue. Where a refund is required by applicable law or expressly provided by this policy, we will provide it.']},
    {heading:'How to request help',body:['Use Contact Us at farazrasool643@gmail.com and include the account email, booking or payment reference, date and a clear description of the issue. Do not send passwords or full card details.']}
  ]},
  contact:{title:'Contact Us',lead:'Need help with UrbanCity, a booking or a policy question? We are happy to hear from you.',sections:[
    {heading:'Support enquiries',body:['Email us at farazrasool643@gmail.com. Please include enough detail for us to understand your request.']},
    {heading:'Booking and payment enquiries',body:['Include your account email, booking or payment reference, date and a short description of the problem. Do not send passwords, authentication codes or full card details.']},
    {heading:'Privacy requests',body:['For privacy or personal-data requests, contact farazrasool643@gmail.com and clearly state that your request concerns personal data. We may need to verify your identity before completing the request.']},
    {heading:'Operator',body:['UrbanCity is operated by Faraz as a SaaS service based in India. No separate public business phone number, registration number or GST/VAT number is currently provided on this site.']}
  ]},
  pricing:{title:'Pricing',lead:'UrbanCity shows the applicable price before you proceed to payment.',sections:[
    {heading:'Advertising space pricing',body:['Current starting prices are: Corner — $0.50 per 30 minutes; Wall — $0.69 per 30 minutes; Main — $0.90 per 30 minutes. Pricing can vary by advertising space, duration and package. The current price for the selected booking is displayed inside the booking panel before checkout.']},
    {heading:'What you pay',body:['UrbanCity prices are displayed in USD and are currently shown before applicable taxes. The payment checkout may display the payable amount in another currency depending on the payment provider and payment setup. Always review the final amount presented immediately before payment.']},
    {heading:'Booking duration',body:['Bookings are available in 30-minute increments, up to a maximum duration of two days. The booking period begins when payment is successfully confirmed.']},
    {heading:'Price changes',body:['Future prices or packages may change. A change does not alter a booking that has already been successfully confirmed unless required to correct a clear error or permitted by applicable law.']},
    {heading:'Advertising performance',body:['Prices purchase advertising placement/time, not a guaranteed number of visitors, impressions, clicks, leads, conversions or sales. Visitor and footfall figures shown by UrbanCity may change and are provided for informational purposes.']}
  ]}
};

const LINKS:[PageKey,string][]=[['about','About'],['how-it-works','How It Works'],['faq','FAQ'],['rules','Rules'],['pricing','Pricing'],['terms','Terms & Conditions'],['privacy','Privacy Policy'],['refund-policy','Refund & Cancellation'],['contact','Contact Us']];

export default function PublicPage({page}:{page:PageKey}) {
  const location=useLocation(), data=CONTENT[page];
  return <main className="public-page">
    <nav className="public-nav"><Link to="/" className="public-brand">URBANCITY</Link><Link to="/" className="back-to-city">← Back to City</Link></nav>
    <article className="public-article">
      <div className="public-kicker">URBANCITY • {page.split('-').join(' ').toUpperCase()}</div>
      <h1>{data.title}</h1><p className="public-lead">{data.lead}</p>
      <div className="public-divider"/>
      {data.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2>{s.body.map((p,i)=><p key={i}>{p}</p>)}</section>)}
      <p className="public-updated">Last updated: September 2026</p>
    </article>
    <footer className="public-footer">{LINKS.map(([key,label])=><Link key={key} to={'/'+key} className={location.pathname==='/'+key?'selected':''}>{label}</Link>)}</footer>
  </main>
}
